#! /bin/bash -u

export PATH=`pwd`/scripts:${PATH}

# By default,  do not export frozen/chilly requirements from image. If already set, use that value.
export FREEZE_CHILL=${FREEZE_CHILL:-0}

# ----------------- vvvv less frequently changed inputs vvvv -------------------------------
#

# Select "conda" tool used to install conda package and environments: conda or mamba
#   mamba is largely a drop-in replacement for conda with improved dependency resolution,
#   parallel downloads, and C++ implementation.
export CONDA_VER=conda  # switch to conda while "mamba env export" in install-common is broken

# Additional parameters for image-exec Docker run command, e.g. add mounts here
export IMAGE_RUN_PARS="--rm -e JUPYTER_ENABLE_LAB=yes"

# Image scanning,  report Ubuntu status for this version of Ubuntu
export UBUNTU_TAG="22.04"

# Image scanning,  report CVE's at this severity level and  higher
export IMAGE_VULNERABILITY_LEVEL="medium"

# -------------------------------------------------------------------
# Docker Buildkit has two killer features:
#   1. It can set up caches for package download directories which
#        persist between builds if they're not cleared.
#   2. It can set up multiple builders enabling parallel builds of
#        different missions and build parameters.  See image-build-all.

# Docker requires DOCKER_BUILDKIT=1 to enable buildkit for older Docker
# distributions.   This enables buildkit in general.

export DOCKER_BUILDKIT=1

# Stop/improve buildkit log truncation.
export BUILDKIT_STEP_LOG_MAX_SIZE=10000000   # bytes
export BUILDKIT_STEP_LOG_MAX_SPEED=10000000

export CACHE_DIRS="/var/cache/apt /home/jovyan/.cache /opt/conda/pkgs /home/jovyan/.conda/pkgs"

# ----------------------------------------------------------------------------
# PIP_SWITCHES are passed through to pip by Docker and the pip install scripts
# env-update and env-compile/sync.

export PIP_SWITCHES='--no-color --default-timeout 100'

# ----------------- vvvvvv derived inputs, nominally don't change vvvvvv --------------
# automatically sourced into setup-env

export IMAGE_REPO=spacetelescope/science-platform-${DEPLOYMENT_NAME}
export COMMON_REPO=${IMAGE_REPO}

export JUPYTERHUB_DIR=`pwd`

export IMAGE_DIR=`pwd`/deployments/${DEPLOYMENT_NAME}

export COMMON_IMAGE_DIR=`pwd`/deployments/common

export COMMON_ID=${COMMON_REPO}:${COMMON_TAG}
export IMAGE_ID=${IMAGE_REPO}:${IMAGE_TAG}

# --------------- vvvvv misc env settings vvvvv ---------------------------------

function where () {
    info="${DEPLOYMENT_NAME}-${ENVIRONMENT}"
    if [[ "${USE_FROZEN}" == "0" ]]; then
        info="${info}-floating"
    elif [[ "${USE_FROZEN}" == "1" ]]; then
        info="${info}-frozen"
    elif [[ "${USE_FROZEN}" == "2" ]]; then
        info="${info}-chilly"
    else
        info="${info}-ERROR"
    fi
    if [[ "${CLEAR_PKG_CACHES}" == "1" ]]; then
        info="${info}-clearpkgs"
    else
        info="${info}-keeppkgs"
    fi
    echo $info
}

alias glog="git log --graph --oneline --all --decorate --color --pretty=format:'%C(auto)%h%d (%cr) %cn <%ce> %s' | head -n 30"
