#!/bin/bash

# .............................................................................................
#
# This file is used to initialize $HOME after a notebook session has been spawned.
#
# When running on JupyterHub,  $HOME is backed by and overlay of EFS and AWS features
#   are available.
# When running in Docker,  $HOME is part of the image being initialized for standalone
#   usage.   AWS features are assumed to be unavailable.
#
# ONLY this file should be called from the Dockerfile or hub post start hook.
# When called on jupyterhub, the single optional parameter "on-hub" should be specified
# to enable the initialization of features not needed/supported for standalone ops.
#
# .............................................................................................
# Include multi-mission common behavior
# .............................................................................................
HUB_FLAG=${1:-"on-hub"}

/opt/common-scripts/psh-preamble ${HUB_FLAG}
set +eu   # Do not let init failures block logins

# .............................................................................................
# # CRDS cache setup and sharing
#
# Only a hub installation is guaranteed to have a shared CRDS cache
# which can be exploited by symlinking.  Note that this symlinking
# process is a definite improvement over normal CRDS caching since a
# user's cache can share system files while remaining writable for
# files which are not available globally.
# .............................................................................................
if [[ $HUB_FLAG == "on-hub" ]]; then
    /opt/common-scripts/symlink-crds
    # /opt/common-scripts/kernel-setup
fi

# .............................................................................................
# Sync reference notebook directories / branches.
# .............................................................................................

TC=$HOME/references/tike_content-ref
/opt/common-scripts/git-sync-v4  https://github.com/spacetelescope/tike_content.git  main  ${TC}

MN=$HOME/references/mast_notebooks-ref
/opt/common-scripts/git-sync-v4   https://github.com/spacetelescope/mast_notebooks.git   main  ${MN}

HU=$HOME/references/hellouniverse-ref
/opt/common-scripts/git-sync-v4   https://github.com/spacetelescope/hellouniverse.git   main   ${HU}

PT=$HOME/references/project-tikebook-ref
/opt/common-scripts/git-sync-v4   http://github.com/spacetelescope/project-tikebook.git main   ${PT}

# .............................................................................................
# Define image notebook tests based on installed images.
# Note that doing this dynamically is overwriting the notebooks file defined in the original
# tess tests directory.
# .............................................................................................

mkdir -p /opt/environments/tess/tests

# .............................................................................................
# Remove VNC Desktop from Launcher
# .............................................................................................
rm -rf $HOME/.user-dirs/Desktop
rm -rf $HOME/Desktop

# .............................................................................................
# Configure lightkurve and astropy cache locations for automatic clearing
# .............................................................................................
rm -rf $HOME/.lightkurve-cache
mkdir -p $HOME/.cache \
      $HOME/.lightkurve/cache \
      $HOME/.astropy/cache
cd $HOME/.cache
rm -f astropy lightkurve
ln -s $HOME/.astropy/cache  astropy
ln -s $HOME/.lightkurve/cache  lightkurve

# make sure the script does not fail blocking spawn.
exit 0
