#!/bin/bash

# .............................................................................................
#
# This file is used to initialize $HOME after a notebook session has been spawned.
#
# When running on JupyterHub,  $HOME is backed by and overlay of EFS and AWS features
#   are available.
# When running in Docker,  $HOME is part of the image being initialized for standalone
#   usage.   AWS features are assumed to be unavailable.
#
# ONLY this file should be called from the Dockerfile or hub post start hook.
# When called on jupyterhub, the single optional parameter "on-hub" should be specified
# to enable the initialization of features not needed/supported for standalone ops.
#
# .............................................................................................
# Include multi-mission common behavior
# .............................................................................................
HUB_FLAG=${1:-"on-hub"}

/opt/common-scripts/psh-preamble ${HUB_FLAG}
set +eu   # Do not let init failures block logins

# .............................................................................................
# Initialization of the shared CRDS cache if it exists for this mission.
# .............................................................................................

# .............................................................................................
# Sync reference notebook directories / branches.
# .............................................................................................

TC=/home/jovyan/references/tike_content-ref
/opt/common-scripts/git-sync-v4  https://github.com/spacetelescope/tike_content.git  main  ${TC}

MN=/home/jovyan/references/mast_notebooks-ref
/opt/common-scripts/git-sync-v4   https://github.com/spacetelescope/mast_notebooks.git   main  ${MN}

HU=/home/jovyan/references/hellouniverse-ref
/opt/common-scripts/git-sync-v4   https://github.com/spacetelescope/hellouniverse.git   main   ${HU}

PT=/home/jovyan/references/project-tikebook-ref
/opt/common-scripts/git-sync-v4   http://github.com/spacetelescope/project-tikebook.git main   ${PT}

# .............................................................................................
# Define image notebook tests based on installed images.
# Note that doing this dynamically is overwriting the notebooks file defined in the original
# tess tests directory.
# .............................................................................................

mkdir -p /opt/environments/tess/tests

# Set up test notebooks for TIKE MAST Summer Webbinar 2024 based on JUSI-1607
rm -f /opt/environments/tess/tests/notebooks
for dir_num in  00 01 03 4 7 8 09; do
    find $TC/content/notebooks/webinar-series -name '*.ipynb'  | grep -v live >> /opt/environments/tess/tests/notebooks
done

# DROPPED for MAST Summer Webbinar 2024
# cat <<EOF >/opt/environments/tess/tests/notebooks
#     ${TC}/code/test_notebooks/lts-kernel-testing.ipynb
#     ${TC}/code/test-cloud-lightkurve.py

#     ${MN}/notebooks/astroquery/large_downloads/large_downloads.ipynb
#     ${MN}/notebooks/astroquery/beginner_zcut/beginner_zcut.ipynb
#     ${MN}/notebooks/astroquery/beginner_search/beginner_search.ipynb

#     #${MN}/notebooks/astroquery/historic_quasar_observations/historic_quasar_observations.ipynb
#     #${MN}/notebooks/astroquery/historic_quasar_observations/historic_quasar_observations_SOLUTIONS.ipynb
#     #${MN}/notebooks/IUE/exploring_UV_extinction_curves/exploring_UV_extinction_curves.ipynb

#     ${MN}/notebooks/TESS/interm_tesscut_requests/interm_tesscut_requests.ipynb
#     ${MN}/notebooks/TESS/beginner_tour_lc_tp/beginner_tour_lc_tp.ipynb
#     ${MN}/notebooks/TESS/beginner_tic_search_hd209458/beginner_tic_search_hd209458.ipynb
#     ${MN}/notebooks/TESS/beginner_how_to_use_lc/beginner_how_to_use_lc.ipynb
#     ${MN}/notebooks/TESS/interm_tasoc_lc/interm_tasoc_lc.ipynb
#     ${MN}/notebooks/TESS/interm_gi_query/interm_gi_query.ipynb
#     ${MN}/notebooks/TESS/beginner_how_to_use_tp/beginner_how_to_use_tp.ipynb
#     ${MN}/notebooks/TESS/beginner_tess_exomast/beginner_tess_exomast.ipynb
#     ${MN}/notebooks/TESS/beginner_how_to_use_dvt/beginner_how_to_use_dvt.ipynb
#     ${MN}/notebooks/TESS/beginner_astroquery_dv/beginner_astroquery_dv.ipynb
#     ${MN}/notebooks/TESS/beginner_how_to_use_ffi/beginner_how_to_use_ffi.ipynb
#     ${MN}/notebooks/TESS/asteroid_rotation/asteroid_rotation.ipynb

#     ${MN}/notebooks/TESS/interm_tess_prf_retrieve/interm_tess_prf_retrieve.ipynb
#     ${MN}/notebooks/TESS/removing_scattered_light_using_regression/removing_scattered_light_using_regression.ipynb
#     ${MN}/notebooks/K2/Lightcurve/Lightcurve.ipynb
#     ${MN}/notebooks/K2/TPF/TPF.ipynb
#     ${MN}/notebooks/K2/beginner_how_to_use_ffi/beginner_how_to_use_ffi.ipynb
#     ${MN}/notebooks/Kepler/lightkurve_combining_multiple_quarters/lightkurve_combining_multiple_quarters.ipynb
#     ${MN}/notebooks/Kepler/instrumental_noise_4_electronic_noise/instrumental_noise_4_electronic_noise.ipynb
#     ${MN}/notebooks/Kepler/measuring_a_rotation_period/measuring_a_rotation_period.ipynb
#     ${MN}/notebooks/Kepler/instrumental_noise_3_seasonal_and_detector_effects/instrumental_noise_3_seasonal_and_detector_effects.ipynb
#     ${MN}/notebooks/Kepler/plotting_images_from_tpf/plotting_images_from_tpf.ipynb
#     ${MN}/notebooks/Kepler/identifying_transiting_planet_signals/identifying_transiting_planet_signals.ipynb
#     ${MN}/notebooks/Kepler/verifying_the_location_of_a_signal/verifying_the_location_of_a_signal.ipynb
#     ${MN}/notebooks/Kepler/lightkurve_interactively_inspecting_TPFs_and_LCs/lightkurve_interactively_inspecting_TPFs_and_LCs.ipynb
#     ${MN}/notebooks/Kepler/plotting_catalog_over_FFI/plotting_catalog_over_FFI.ipynb
#     ${MN}/notebooks/Kepler/instrumental_noise_2_spurious_signals_and_time_sampling_effects/instrumental_noise_2_spurious_signals_and_time_sampling_effects.ipynb
#     ${MN}/notebooks/Kepler/plotting_dvts/plotting_dvts.ipynb
#     ${MN}/notebooks/Kepler/how_to_understand_and_manipulate_the_periodogram_of_an_oscillating_star/how_to_understand_and_manipulate_the_periodogram_of_an_oscillating_star.ipynb
#     ${MN}/notebooks/Kepler/instrumental_noise_1_data_gaps_and_quality_flags/instrumental_noise_1_data_gaps_and_quality_flags.ipynb
#     ${MN}/notebooks/Kepler/visualizing_periodic_signals_using_a_river_plot/visualizing_periodic_signals_using_a_river_plot.ipynb
#     ${MN}/notebooks/Kepler/creating_periodograms/creating_periodograms.ipynb
#     ${MN}/notebooks/Kepler/plotting_lightcurves/plotting_lightcurves.ipynb
#     ${MN}/notebooks/Kepler/lightkurve_custom_aperture_photometry/lightkurve_custom_aperture_photometry.ipynb
#     ${MN}/notebooks/Kepler/lightkurve_searching_for_data/lightkurve_searching_for_data.ipynb
#     ${MN}/notebooks/Kepler/how_to_estimate_a_stars_mass_and_radius_using_asteroseismology/how_to_estimate_a_stars_mass_and_radius_using_asteroseismology.ipynb
#     #${MN}/notebooks/HSC/HSCV3_API/hscv3_api.ipynb
#     #${MN}/notebooks/HSC/HCV_CASJOBS/HCV_casjobs_demo.ipynb
#     #${MN}/notebooks/HSC/HSC_TAP/HSC_TAP.ipynb
#     #${MN}/notebooks/HSC/SWEEPS_HSCV3P1_API/sweeps_hscv3p1_api.ipynb
#     #${MN}/notebooks/HSC/HSCV3_SMC_API/hscv3_smc_api.ipynb
#     #${MN}/notebooks/HSC/HCV_API/HCV_API_demo.ipynb
#     #${MN}/notebooks/HSC/SWEEPS_HSCV3P1/sweeps_hscv3p1.ipynb
#     #${MN}/notebooks/JWST/Engineering_Database_Retreival/EDB_Retrieval.ipynb
#     #${MN}/notebooks/JWST/SI_keyword_exoplanet_search/SI_keyword_exoplanet_search.ipynb
#     #${MN}y/notebooks/JWST/download_by_program_id/download_by_program_id.ipynb
#     ${MN}/notebooks/K2/removing_instrumental_noise_using_pld/removing_instrumental_noise_using_pld.ipynb
#     ${HU}/notebooks.ipynb
#     ${HU}/notebooks/hello-universe/Classifying_PanSTARRS_sources_with_unsupervised_learning/Classifying_PanSTARRS_sources_with_unsupervised_learning.ipynb
#     ${HU}/notebooks/hello-universe/Regressing_3D-HST_galaxy_redshift_with_decision_trees/Regressing_3D-HST_galaxy_redshift_with_decision_trees.ipynb
# EOF

# .............................................................................................
# These are tests we'd like to run which fail for various reasons.
# These can be run in the container with:
#      /opt/common-scripts/test-notebooks tess `cat /opt/environments/test/tests/notebooks-failing`
# Note that some of these fail due to the 7G pipeline memory requirement
# .............................................................................................

# cat <<EOF >/opt/environments/tess/tests/notebooks-failing
#     ${MN}/notebooks/TESS/asteroid_rotation/asteroid_rotation_soutions.ipynb
#     ${MN}/notebooks/TESS/beginner_tesscut_astroquery/beginner_tesscut_astroquery.ipynb
#     ${MN}/notebooks/MCCM/FIMS-SPEAR/hyperspectral_healpix_maps/hyperspectral_healpix_maps.ipynb
#     ${MN}/notebooks/TESS/beginner_tess_tap_search/beginner_tess_tap_search.ipynb
#     ${MN}/notebooks/PanSTARRS/PS1_DR2_TAP/PS1_DR2_TAP.ipynb
#     ${MN}/notebooks/astrocut/making_tess_cubes_and_cutouts/making_tess_cubes_and_cutouts.ipynb
# EOF

# # .............................................................................................
# # This runs for e.g. 30 min
# # .............................................................................................
# cat <<EOF >/opt/environments/tess/tests/long-notebooks-failing
#     ${MN}/notebooks/TESS/interm_tesscut_dss_overlay/interm_tesscut_dss_overlay.ipynb
# EOF

# # .............................................................................................
# # Disabled notebooks after priority packages due to not available libraries
# # .............................................................................................
# cat <<EOF >/opt/environments/tess/tests/notebooks-with-no-required-libraries
#     ${HU}/notebooks/hello-universe/Classifying_JWST-HST_galaxy_mergers_with_CNNs/Classifying_JWST-HST_galaxy_mergers_with_CNNs.ipynb
#     ${HU}/notebooks/hello-universe/Classifying_TESS_flares_with_CNNs/Classifying_TESS_flares_with_CNNs.ipynb
# EOF

# .............................................................................................

# /opt/common-scripts/set-notebook-kernel tess  `cat /opt/environments/tess/tests/notebooks`
# /opt/common-scripts/set-notebook-kernel tess  `cat /opt/environments/tess/tests/notebooks-failing`

# /opt/common-scripts/set-notebook-kernel tess  `cat /opt/environments/tess/tests/long-notebooks`
# /opt/common-scripts/set-notebook-kernel tess  `cat /opt/environments/tess/tests/long-notebooks-failing`

# .............................................................................................
# Remove VNC Desktop from Launcher
# .............................................................................................
rm -rf /home/jovyan/.user-dirs/Desktop
rm -rf /home/jovyan/Desktop

# .............................................................................................
# Configure lightkurve and astropy cache locations for automatic clearing
# .............................................................................................
rm -rf /home/jovyan/.lightkurve-cache
mkdir -p /home/jovyan/.cache \
      /home/jovyan/.lightkurve/cache \
      /home/jovyan/.astropy/cache
cd /home/jovyan/.cache
rm -f astropy lightkurve
ln -s /home/jovyan/.astropy/cache  astropy
ln -s /home/jovyan/.lightkurve/cache  lightkurve
