#! /bin/bash

# Generic scripts to git-sync repos for notebooks specified in wrangler spec; no parameters

if [[ "${GIT_SYNC_OFF}" == "1" ]]; then
    echo "git-sync is turned off globally.  aborting sync of notebook repos."
    exit 0
fi

mamba activate base

for url_ref in $(nbw /opt/environments/nbw-wrangler-spec.yaml --print-repo-tags --quiet); do
    url=$(echo $url_ref | cut -d ' ' -f 1)
    ref=$(echo $url_ref |  cut -d ' ' -f 2)
    ref=${GIT_SYNC_OVERRIDE_TAG:-${ref}}
    out=$(basename $url | perl -p -e's/\.git//g')
    /opt/common-scripts/git-sync-v4 ${url} main ${HOME}/references/${out}   # -ref
done
