#! /bin/bash

# Generic scripts to git-sync repos for notebooks specified in wrangler spec; no parameters

if [[ "${GIT_SYNC_OFF}" == "1" ]]; then
    echo "git-sync is turned off globally.  aborting sync of notebook repos."
    exit 0
fi

mamba activate base

while IFS= read -r line; do
  read -r url ref <<<"$line"
  echo "url=$url ref=$ref"
  ref=${GIT_SYNC_OVERRIDE_TAG:-${ref}}
  clone_dir=$(basename $url | perl -p -e's/\.git//g')
  /opt/common-scripts/git-sync-v4 ${url} ${ref} ${HOME}/references/${clone_dir}
done < <(nbw /opt/environments/nbw-wrangler-spec.yaml --print-repo-tags --quiet)
