#! /bin/bash
# .............................................................................................
# Configure jupyter-app-launcher for custom launcher items
# .............................................................................................
echo "Installing jupyter_app_launcher.yaml"
mkdir -p $HOME/.local/share/jupyter/jupyter_app_launcher/
cp /opt/environments/jp_app_launcher.yaml $HOME/.local/share/jupyter/jupyter_app_launcher/
