#!/bin/bash

set -u

# .............................................................................................
#
# This file is used to initialize $HOME after a notebook session has been spawned.
#
# When running on JupyterHub,  $HOME is backed by and overlay of EFS and AWS features
#   are available.
# When running in Docker,  $HOME is part of the image being initialized for standalone
#   usage.   AWS features are assumed to be unavailable.
#
# ONLY this file should be called from the Dockerfile or hub post start hook.
# When called on jupyterhub, the single optional parameter "on-hub" should be specified
# to enable the initialization of features not needed/supported for standalone ops.
#
# .............................................................................................
# Include multi-mission common behavior
# .............................................................................................
HUB_FLAG=${1:-"on-hub"}

/opt/common-scripts/psh-preamble ${HUB_FLAG}
set +e   # Do not let init failures block logins

# .............................................................................................
# CRDS cache setup and sharing
#
# Only a hub installation is guaranteed to have a shared CRDS cache
# which can be exploited by symlinking.  Note that this symlinking
# process is a definite improvement over normal CRDS caching since a
# user's cache can share system files while remaining writable for
# files which are not available globally.
# .............................................................................................
if [[ $HUB_FLAG == "on-hub" ]]; then
    /opt/common-scripts/symlink-crds
    /opt/common-scripts/kernel-setup
fi

# .............................................................................................
# Legacy feature cleanup:  Remove VNC Desktop from Launcher
# .............................................................................................
rm -rf $HOME/.user-dirs/Desktop
rm -rf $HOME/Desktop

/opt/common-scripts/remove-kernel masterclass
/opt/common-scripts/remove-kernel jwebbinar
/opt/common-scripts/remove-kernel jdaviz
/opt/common-scripts/remove-kernel mirisim

# .............................................................................................
# Notebook setup
# .............................................................................................
cd $HOME
/opt/common-scripts/git-sync-v4 https://github.com/spacetelescope/jwebbinar_prep \
                                main \
                                $HOME/references/jwebbinar_prep-ref

mkdir -p /opt/environments/jwebbinar41/test
find $HOME/references/jwebbinar_prep-ref/jwebbinar41 -type f | grep Setup.ipynb >/opt/environments/jwebbinar41/test/notebooks
find $HOME/references/jwebbinar_prep-ref/jwebbinar41 -type f | grep 'Notebook' | grep ipynb >>/opt/environments/jwebbinar41/test/notebooks
chmod -R 775 /opt/environments/jwebbinar41
chmod -R 775 /opt/environments/jwebbinar41/test
chmod 664 /opt/environments/jwebbinar41/test/notebooks
