#! /usr/bin/env python

"""Clear the entire astropy cache."""

import subprocess

def run(cmd, cwd=".", timeout=120):
    """Run subprocess `cmd` in dir `cwd` failing if not completed within `timeout` seconds
    of if `cmd` returns a non-zero exit status.

    Returns both stdout+stderr from `cmd`.
    """
    # print("Running command:", cmd.split())
    result = subprocess.run(
        cmd.split(),
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=True,
        cwd=cwd,
        timeout=timeout,
    )  # maybe succeeds
    return result.stdout


def rm_files(path):
    filepaths = run(f"find -L {path} -type f").splitlines()
    run(f"rm -f {' '.join(filepaths)}")


def clear_cache():
    try:
        import astropy.utils.data
        ap_cache = astropy.config.paths.get_cache_dir()
        print(f"Clearing astropy cache {ap_cache}.")
        astropy.utils.data.clear_download_cache()
    except Exception:
        pass
    try:
        import lightkurve.config
        lk_cache = lightkurve.config.get_cache_dir()
        print(f"Clearing lightkurve cache {lk_cache}.")
        rm_files(lk_cache)
    except Exception:
        pass


if __name__ == "__main__":
    clear_cache()
