#! /bin/bash

set -eu

source `dirname $0`/kernel-utils

usage "$# -lt 1" "<environment-name> [<display-name>] [<env-root>]"  <<EOU
Create virtual environment <environment-name> and add a JupyterLab kernel <display-name> corresponding to it.
If <display-name> is not specified, defaults to <environment-name>.
<env-root> is the root directory for collections of environments, defaulting to $HOME/envs.
EOU

ENVNAME=$1
DISPNAME=${2:-${ENVNAME}}
ENVROOT=${3:-${ENVROOT}}
ENVDIR=${ENVROOT}/venv/${ENVNAME}

banner "Creating virtual environment ${ENVNAME} at ${ENVDIR}"
python -m venv ${ENVDIR}
source kernel-activate ${ENVNAME} "${ENVROOT}"
pip install --upgrade ipykernel pip

echo "---------------------------------------------------------------"
kernel-install "${ENVNAME}"  "${DISPNAME}"
banner "Activate virtual environment with: 'source kernel-activate ${ENVNAME}'"
