#! /bin/bash

# NO set -eu for source script

ENVROOT=${ENVROOT:-${HOME}/envs}
ENVROOTS=${ENVROOTS:-"${ENVROOT} /opt/conda/envs"}   # To add team conda environments?

KERNEL_SHELL=${KERNEL_SHELL:-bash}   # shell nominally used for conda init

function usage() {
   local condition=$1
   shift
   if [ ${condition} ]; then
      echo
      echo "usage: `basename $0` $*"
      echo
      echo "$(cat)"
      echo
      exit 2
   fi
}

function banner() {
    echo "---------------------------------------------------------------"
    echo $*
}
