#! /bin/bash

# NO set -eu for source script

source /opt/tools/kernel-utils

if [ $# -lt 1 ]; then
    echo "usage:  source kernel-deactivate <env-name>  <env-root... (ignored)>"
    # no exit for source script.
else
    ENVNAME=$1
    shift;
    ENVROOTS=${*:-${ENVROOTS}}  # Add team env roots here
    deactivated=false
    for ENVROOT in ${ENVROOTS}; do
        if [ ! -d ${ENVROOT} ]; then
            banner "WARNING:  ${ENVROOT} is not a directory"
	        # some other root may hit though
        elif [ -d ${ENVROOT}/venv/${ENVNAME} ]; then
            deactivate
            deactivated=true
            break
        elif [ -d ${ENVROOT}/conda/${ENVNAME} ]; then
            conda deactivate
            deactivated=true
            break
        else
            /opt/conda/bin/deactivate
            deactivated=true
            break
        fi
    done
    if [ ! ${deactivated} ]; then
        banner "ERROR:  ${ENVNAME} is not a valid environment to deactivate under ${ENVROOTS}."
        # No exit for source script.
    fi
fi
