#! /bin/bash

source /opt/tools/kernel-utils

if [ $# -lt 1 ]; then
    echo "usage:  source kernel-activate <env-name> [<env-root...>]"
    # can't exit in source'd script
else
	source /opt/conda/etc/profile.d/conda.sh

    ENVNAME=$1
    shift;
    ENVROOTS=${*:-${ENVROOTS}}  # Add team env roots here
	activated=false
    for ENVROOT in ${ENVROOTS}; do
	    if [ ! -d ${ENVROOT} ]; then
			banner "Kernel environments directory ${ENVROOT} does not exist."
			continue
	    elif [ -d ${ENVROOT}/venv/${ENVNAME} ]; then
			source ${ENVROOT}/venv/${ENVNAME}/bin/activate
			activated=true
			break
	    elif [ -d ${ENVROOT}/conda/${ENVNAME} ]; then
			conda activate ${ENVROOT}/conda/${ENVNAME}
			activated=true
			break
	    elif [ -d ${ENVROOT}/${ENVNAME} ]; then
			conda activate ${ENVNAME}
			activated=true
			break
	    fi
    done
	if [ "${activated}" == "false" ]; then
		banner "Kernel environment ${ENVNAME} not found under ${ENVROOTS}."
	fi
fi
