#! /bin/bash

# set -eu

KERNEL_TOOLS=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source  ${KERNEL_TOOLS}/kernel-utils

usage "$# -lt 1"  "<environment-name> [<display-name>]"  <<EOU
Add existing compute environment <environment-name> to JupyterLab as kernel <display-name>.
The compute environment is either a ${CONDA_VER} environment or a virtualenv.
If <display-name> is not specified,  the kernel will be named <environment-name> in JupyterLab.
EOU

ENVNAME=$1
DISPNAME="${2:-${ENVNAME}}"

source ${KERNEL_TOOLS}/kernel-activate ${ENVNAME}  >& /dev/null

echo "Adding kernel ${DISPNAME} corresponding to Python environment ${ENVNAME}"
python -m ipykernel install --user --name="${ENVNAME}"  --display-name "${DISPNAME}"

