#! /bin/bash

# set -eu

KERNEL_TOOLS=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
source  ${KERNEL_TOOLS}/kernel-utils

usage "$# -lt 2"  "<environment-name>   <specname.yaml>"  <<EOU
Generate a ${CONDA_VER} installation YAML spec for <environment-name> which can be used
to install it somewhere else with its full complement of installed packages.

Save environment to <specname.yaml>:

$ kernel-export  test-1  test-1-env-spec.yml

Rebuild it somewhere else where ${CONDA_VER} is already installed,  e.g. the science platform
in a different account:

$ kernel-create  test-1  test-1-env-spec.yml
EOU

ENVNAME="$1"
SPECNAME="$2"

source ${KERNEL_TOOLS}/kernel-activate ${ENVNAME}  >& /dev/null

echo "Exporting environment ${ENVNAME} to ${SPECNAME}"
# --from-history 

${CONDA_VER} env export -p  $CONDA_PREFIX  | grep -v "^prefix:"  > ${SPECNAME}


