#!/bin/bash

# NO set -eu for source script

ENVROOT=${ENVROOT:-${HOME}/envs}
ENVROOTS=${ENVROOTS:-${ENVROOT} /opt/conda/envs}   # To add team conda environments?

function usage() {
   if `eval [[ $1 ]]`; then
      shift
      echo "usage: `basename $0` $*"
      exit 2
   fi
}

function banner() {
    echo "---------------------------------------------------------------"
    echo $*
    echo "---------------------------------------------------------------"
}
