#! /bin/bash

source /opt/tools/kernel-utils

if [ $# -ne 1 ]; then
    echo "usage:  source kernel-deactivate <env-name>"
else
    ENVNAME=$1

    ENVDIR=`find ${ENVROOT} -name ${ENVNAME} -type d`

    if [[ ${ENVNAME} != "" ]]; then
	if echo ${ENVDIR} | grep -q ${ENVROOT}/venv; then
            deactivate
	elif echo ${ENVDIR} | grep -q ${ENVROOT}/conda; then
            conda deactivate
	else
            /opt/conda/bin/deactivate
	fi
    fi
fi
