#!/bin/bash

# set -u

# .............................................................................................
#
# This file is used to initialize $HOME after a notebook session has been spawned.
#
# When running on JupyterHub,  $HOME is backed by and overlay of EFS and AWS features
#   are available.
# When running in Docker,  $HOME is part of the image being initialized for standalone
#   usage.   AWS features are assumed to be unavailable.
#
# ONLY this file should be called from the Dockerfile or hub post start hook.
# When called on jupyterhub, the single optional parameter "on-hub" should be specified
# to enable the initialization of features not needed/supported for standalone ops.
#
# .............................................................................................
# Include multi-mission common behavior
# .............................................................................................
HUB_FLAG=${1:-"on-hub"}

/opt/common-scripts/psh-preamble ${HUB_FLAG}
set +e   # Do not let init failures block logins

# .............................................................................................
# # CRDS cache setup and sharing
#
# Only a hub installation is guaranteed to have a shared CRDS cache
# which can be exploited by symlinking.  Note that this symlinking
# process is a definite improvement over normal CRDS caching since a
# user's cache can share system files while remaining writable for
# files which are not available globally.
# .............................................................................................
if [[ $HUB_FLAG == "on-hub" ]]; then
    /opt/common-scripts/symlink-crds
    # /opt/common-scripts/kernel-setup
fi
# .............................................................................................
# Sync reference notebook directories / branches.
# .............................................................................................

# .............................................................................................
# Roman-cal Phase 1
# .............................................................................................

/opt/common-scripts/git-sync-v4 https://github.com/spacetelescope/roman_notebooks \
                                main \
                                $HOME/references/roman_notebooks

# .............................................................................................
# Remove old/unused kernels from UI selection
# .............................................................................................
/opt/common-scripts/remove-kernel jdaviz

# .............................................................................................
# Test notebook setup if applicable
# .............................................................................................
