#! /bin/bash

# This is a simplified test script based on the wrangler's "single mission kernel"
# model that leverages having the wrangler spec for the environment available in order
# to run wrangler import and notebook tests.

TEST_TYPES=${1:-"--test-imports"}

if [ $# -ge 1 ]; then
    shift;
fi

cd /tmp
source /opt/common-scripts/env-activate base
python -m nb_wrangler  /opt/environments/nbw-wrangler-spec.yaml  --repos-dir /tmp/nb-wrangler-test-clones --clone-repos ${TEST_TYPES}  $*
rm -rf /tmp/nb-wrangler-test-clones
