#! /usr/bin/env python

import sys
import os


def add_mounts_to_run(dockerfile, mount_dirs):
    with open(dockerfile) as file:
        result = ""
        for line in file:
            if "RUN " in line:
                for mount in mount_dirs:
                    line = line.replace(
                        "RUN ", f"RUN --mount=type=cache,mode=0777,target={mount} "
                    )
            result += line
    print(result)


if __name__ == "__main__":
    cache_dirs = os.environ.get("CACHE_DIRS").split() or sys.argv[2:]
    add_mounts_to_run(sys.argv[1], cache_dirs)
