#! /bin/bash -eu

HELP=${1:-""}

if [[ ${HELP}  == "--help" ]]; then
    echo "usage: `basename $0` [--dev] [<image-tag-or-hash>]"
    exit 2
fi

source image-dev-pars

# If no image is specified, run the last tagged mission container.
export EXEC_ID=${1:-`docker image ls -q | head -1`}

# Both normal and --dev mode are interactive
export IMAGE_RUN_PARS="$IMAGE_RUN_PARS -it"

image-exec /bin/bash --rcfile /etc/bash.bashrc
