#! /bin/bash

set -eu

# If desired,  $1 can override the default image type
export IMAGE_ID=${1:-${NOTEBOOK_ID}}
export MAMBA=${2:-"micromamba"}
export WHERE=${2:-"on-github"}

if [[ "$(which grype)" == "" ]]; then
    echo "The 'syft' SBOM scanner is not installed.  Installing..."
    ${MAMBA} install --yes --quiet -c conda-forge  syft
    echo "The 'grype' image vulnerability scanner program is not installed.  Installing..."
    ${MAMBA} install --yes --quiet -c conda-forge  grype
fi

function f_grype {
    KIND=${1:-"--only-fixed"}
    LEVELS=${2:-"high,critical"}
    THRESHOLD=$(echo ${LEVELS} | sed 's/,/|/g')
    if [ ! -e /tmp/syft.sbom ]; then
        syft --output syft-json $IMAGE_ID | cat >/tmp/syft.sbom
    fi
    cat /tmp/syft.sbom | grype --by-cve --output table --fail-on $THRESHOLD | grep -i -E ${LEVELS}
}

function annotated_echo {
    if [[ $WHERE == "on-github" ]]; then
        ANN_PREFIX="::warning "
        echo "::warning $*"
    else
        echo "$*"
    fi
}

echo "scanfailed" >/tmp/grype-tag   # this may be impossible but just in case

set -o pipefail         # do not stop if f_grype fails in a pipe
set +e                  # do not stop on error

f_grype --only-fixed high,critical
if [ $? -ne 0 ]; then
    annotated_echo "===> Grype scan FAILED w/o --only-fixed."
    f_grype --only-unfixed high,critical
    if [ $? -ne 0 ]; then
        annotated_echo "===> Grype scan FAILED with --only-fixed."
        echo "hasfixed" >/tmp/grype-tag
    else
        annotated_echo "===> Grype scan PASSED with --only-unfixed."
        echo "hasunfixed" >/tmp/grype-tag
    fi
    exit 1
else
    echo "===> Grype scan PASSED even w/o --only-fixed."
    echo "scanok" >/tmp/grype-tag
fi
exit 0
