#! /usr/bin/env python

import argparse
import re
import shutil


def create_setup_env_file(
    platform, deployment_name, environment, use_frozen, freeze, cal_version, owner
):
    shutil.copy("setup-env.template", "setup-env")

    use_frozen = {"floating": "0", "frozen": "1"}.get(use_frozen, use_frozen)

    with open("setup-env", "r") as file:
        content = file.read()

        content = re.sub(
            r"DEPLOYMENT_NAME=.+",
            f"DEPLOYMENT_NAME={deployment_name}",
            content,
        )

        content = re.sub(
            r"PLATFORM=.+",
            f"PLATFORM={platform}",
            content,
        )

        content = re.sub(
            r"ENVIRONMENT=.+",
            f"ENVIRONMENT={environment}",
            content,
        )

        content = re.sub(r"USE_FROZEN=[\d]", f"USE_FROZEN={use_frozen}", content)

        content = re.sub(r"FREEZE=[\d]", f"FREEZE={freeze}", content)

        content = re.sub(r"CAL_VERSION=.+", f"CAL_VERSION={cal_version}", content)

        content = re.sub(r"OWNER=.+", f"OWNER={owner}", content)
        if owner == "spacetelescope":
            content = re.sub(r"REGISTRY=.+", 'REGISTRY=""', content)
        else:
            content = re.sub(r"REGISTRY=.+", f'REGISTRY="{owner}"', content)

    with open("setup-env", "w+") as file:
        file.write(content)

    print(content)


def main():
    parser = argparse.ArgumentParser(
        description="Create setup-env file to define image build properties."
    )
    parser.add_argument(
        "deployment",
        choices=["tike", "roman", "jwebbinar"],
        help="The deployment name defining image contents.",
    )
    parser.add_argument(
        "--environment",
        choices=["sandbox", "dev", "test", "prod", "int"],
        default="sandbox",
        help="The deployment name defining image contents.",
    )
    parser.add_argument(
        "--platform",
        choices=["linux/amd64", "linux/aarch64"],
        default="linux/amd64",
        help="The OS/instruction-set for building and running images.",
    )
    parser.add_argument(
        "--use-frozen",
        type=str,
        choices=["0", "1", "floating", "frozen"],
        default="floating",
        help="Use floating (default: 0).",
    )
    parser.add_argument(
        "--freeze",
        type=int,
        default=0,
        choices=[0, 1],
        help="Don't freeze requirements, let them float to highest versions possible (default: 0).",
    )
    parser.add_argument(
        "--cal-version",
        default="none",
        help="Calibration s/w version when applicable (default: none).",
    )
    parser.add_argument(
        "--owner",
        type=str,
        default="spacetelescope",
        choices=["spacetelescope", "quay.io/jupyter"],
        help="Repo used to build or pull scipy-notebook image,  spacetelescope(build) or quay.io/jupyter(pull)",
    )
    args = parser.parse_args()

    create_setup_env_file(
        args.platform,
        args.deployment,
        args.environment,
        args.use_frozen,
        args.freeze,
        args.cal_version,
        args.owner,
    )


if __name__ == "__main__":
    main()
