#! /bin/bash

set -eu

echo "========================= Building Base Image ========================"

# These build-args are added to the image environment and will be available in
#   all subsequent builds based on this image.

OWNER=stsci-jh

cd ${JUPYTERHUB_DIR}/deployments/common/image
docker build --progress plain --tag ${OWNER}/ubuntu-base --file Dockerfile.base \
       --build-arg USE_FROZEN=${USE_FROZEN} \
       --build-arg PIP_SWITCHES="${PIP_SWITCHES}" \
       --build-arg CLEAR_PKG_CACHES="${CLEAR_PKG_CACHES}" \
       --build-arg CONDA_VER=${CONDA_VER} \
       --build-arg ROOT_CONTAINER=ubuntu:${IMAGE_UBUNTU_NAME} \
       .

cd ~
if [[ ! -d docker-stacks ]]; then
    git clone https://github.com/jupyter/docker-stacks.git
    cd docker-stacks
else
    cd docker-stacks
    git fetch origin
    git stash
    git checkout origin/main
fi

# checkout the appropriate docker-stacks revision if using frozen specs;
# otherwise, collect and stash revision
env_frozen_dir="${IMAGE_DIR}/env-frozen"
mkdir -p $env_frozen_dir
frozen_hash_spec="$env_frozen_dir/docker-stacks.hash"
if [[ "$USE_FROZEN" == "1" ]]; then
    git checkout `cat $frozen_hash_spec`
else
    if [[ "$FREEZE_CHILL" == "1" ]]; then
        echo `git rev-parse HEAD` > $frozen_hash_spec
    fi
fi

# Taken from the docker-stacks Makefile to enable adding --build-arg's again
build_jh() {
    STACK=$1;  shift
    docker build --rm --force-rm -t ${OWNER}/${STACK}:latest ./${STACK} --build-arg OWNER=${OWNER} --progress plain $*
}

build_jh  docker-stacks-foundation  --build-arg ROOT_CONTAINER=${OWNER}/ubuntu-base:latest

build_jh  base-notebook     --build-arg ROOT_CONTAINER=${OWNER}/docker-stacks-foundation:latest

build_jh  minimal-notebook  --build-arg BASE_CONTAINER=${OWNER}/base-notebook:latest

build_jh  scipy-notebook    --build-arg BASE_CONTAINER=${OWNER}/minimal-notebook:latest
