#! /bin/bash

set -eu

#     usage:  image-cp   <path-inside-container>   [<path-on-host> or PWD]
#
#     Copy the specified filepath out of the currently configured image
#     to the specified location on the host or the PWD.

PATH_TO_EXPORT=$1
WHERE_TO_PUT_IT=${2:-`pwd`}
ACTUAL_IMAGE=${3:-${IMAGE_ID}}

CONTAINER=$(docker run -d ${ACTUAL_IMAGE} /bin/bash)

docker cp ${CONTAINER}:${PATH_TO_EXPORT}  ${WHERE_TO_PUT_IT}

docker container rm ${CONTAINER}  >& /dev/null
