#! /bin/bash

set -eu

echo "========================= Building Base Image ========================"

# These build-args are added to the image environment and will be available in
#   all subsequent builds based on this image.

cd ~
if [[ ! -d docker-stacks ]]; then
    git clone https://github.com/jupyter/docker-stacks.git
    cd docker-stacks
else
    cd docker-stacks
    git fetch origin
    set +e
    git stash
    git checkout origin/main
    git stash pop
    set -e
fi

# checkout the appropriate docker-stacks revision if using frozen specs;
# otherwise, collect and stash revision
env_frozen_dir="${IMAGE_DIR}/env-frozen"
mkdir -p $env_frozen_dir
frozen_hash_spec="$env_frozen_dir/docker-stacks.hash"
if [[ "$USE_FROZEN" == "1" ]]; then
    git checkout `cat $frozen_hash_spec`
else
    if [[ "$FREEZE_CHILL" == "1" ]]; then
        echo `git rev-parse HEAD` > $frozen_hash_spec
    fi
fi

# Taken from the docker-stacks Makefile to enable adding --build-arg's again
build_jh() {
    STACK=$1;  shift
    add-caching images/${STACK}/Dockerfile >images/${STACK}/Dockerfile.cached
    docker build --rm --force-rm -t ${OWNER}/${STACK}:latest ./images/${STACK} --file images/${STACK}/Dockerfile.cached --build-arg OWNER=${OWNER} --progress plain $*
}

build_jh  docker-stacks-foundation  --build-arg ROOT_CONTAINER=ubuntu:${UBUNTU_TAG}

build_jh  base-notebook     --build-arg BASE_CONTAINER=${OWNER}/docker-stacks-foundation:latest

build_jh  minimal-notebook  --build-arg BASE_CONTAINER=${OWNER}/base-notebook:latest

build_jh  scipy-notebook    --build-arg BASE_CONTAINER=${OWNER}/minimal-notebook:latest
