#! /usr/bin/env bash

# Search for files containing Python source code and print their names

cd ${JUPYTERHUB_DIR}

DIRS=${1:-"deployments scripts"}

(

# Find Python she-bang scripts w/o .py extension
find ${DIRS}  -type f | xargs grep -l -E '#!\s*/usr/bin/env\s+python'

# Find standard Python source code files
find ${DIRS}  -name '*\.py'

) | grep -v default-home-contents
