#! /usr/bin/env bash

# Run code quality tool flake8 on all python sources which can be found

cd $JUPYTERHUB_DIR

echo "flake8 version:"  `flake8 --version`
flake8  --max-line-length 120  --ignore E302,E203,E305,W291,W503,W504,W391,E501 --count  --statistics  `sscan-find-python-files`
