#! /bin/bash -eu

HERE=`dirname $0`

cd $HERE

cd ../deployments
DEPLOYMENTS=$(ls -1 | grep -v common)

cd $HERE/..
for deployment in $DEPLOYMENTS; do
    $HERE/image-configure $deployment
    source setup-env
    image-update
done

