#! /bin/bash -eux

HERE=$(dirname `realpath $0`)

cd $HERE

cd ../deployments
DEPLOYMENTS=$(ls -1 | grep -v common)

cd $HERE/..
for deployment in $DEPLOYMENTS; do
    $HERE/image-configure $deployment --freeze 1 --use-frozen 0
    source setup-env
    case $1 in
	--build)
	    image-build
	;;
	*)
	    image-update
	;;
    esac
done

