#!/usr/bin/env bash
# Generated by nb-wrangler for asset installation during Docker build
set -e

cd /opt/environments

# Asset 0: directory assets/roman/ -> /opt/environments/
echo "Installing asset directory assets/asset_0/roman to /opt/environments/..."
mkdir -p "/opt/environments/"
cp -r "assets/asset_0/roman"/. "/opt/environments//"

# Asset 1: directory assets/generic/ -> /opt/environments/
echo "Installing asset directory assets/asset_1/generic to /opt/environments/..."
mkdir -p "/opt/environments/"
cp -r "assets/asset_1/generic"/. "/opt/environments//"

# Asset 2: file assets/generic/stop_server_ext.json -> /etc/jupyter/jupyter_server_config.d/
echo "Installing asset file assets/asset_2/stop_server_ext.json to /etc/jupyter/jupyter_server_config.d/..."
if [ -d "/etc/jupyter/jupyter_server_config.d/" ] || [[ "/etc/jupyter/jupyter_server_config.d/" == */ ]]; then
    mkdir -p "/etc/jupyter/jupyter_server_config.d/"
    cp "assets/asset_2/stop_server_ext.json" "/etc/jupyter/jupyter_server_config.d//"
else
    mkdir -p "$(dirname "/etc/jupyter/jupyter_server_config.d/")"
    cp "assets/asset_2/stop_server_ext.json" "/etc/jupyter/jupyter_server_config.d/"
fi

# Asset 3: file assets/generic/stop_server_ext.py -> /srv/jupyter/
echo "Installing asset file assets/asset_3/stop_server_ext.py to /srv/jupyter/..."
if [ -d "/srv/jupyter/" ] || [[ "/srv/jupyter/" == */ ]]; then
    mkdir -p "/srv/jupyter/"
    cp "assets/asset_3/stop_server_ext.py" "/srv/jupyter//"
else
    mkdir -p "$(dirname "/srv/jupyter/")"
    cp "assets/asset_3/stop_server_ext.py" "/srv/jupyter/"
fi

