#!/usr/bin/env bash
# Generated by nb-wrangler for asset installation during Docker build
set -e

cd /opt/environments

# Asset 0: file assets/generic/catalog-schema-browser.ipynb -> /opt/environments
echo "Installing asset file assets/asset_0/catalog-schema-browser.ipynb to /opt/environments..."
if [ -d "/opt/environments" ] || [[ "/opt/environments" == */ ]]; then
    mkdir -p "/opt/environments"
    cp "assets/asset_0/catalog-schema-browser.ipynb" "/opt/environments/"
else
    mkdir -p "$(dirname "/opt/environments")"
    cp "assets/asset_0/catalog-schema-browser.ipynb" "/opt/environments"
fi

# Asset 1: file assets/roman/cost-dashboard.ipynb -> /opt/environments
echo "Installing asset file assets/asset_1/cost-dashboard.ipynb to /opt/environments..."
if [ -d "/opt/environments" ] || [[ "/opt/environments" == */ ]]; then
    mkdir -p "/opt/environments"
    cp "assets/asset_1/cost-dashboard.ipynb" "/opt/environments/"
else
    mkdir -p "$(dirname "/opt/environments")"
    cp "assets/asset_1/cost-dashboard.ipynb" "/opt/environments"
fi

# Asset 2: file assets/generic/stop_server_ext.json -> /etc/jupyter/jupyter_server_config.d/
echo "Installing asset file assets/asset_2/stop_server_ext.json to /etc/jupyter/jupyter_server_config.d/..."
if [ -d "/etc/jupyter/jupyter_server_config.d/" ] || [[ "/etc/jupyter/jupyter_server_config.d/" == */ ]]; then
    mkdir -p "/etc/jupyter/jupyter_server_config.d/"
    cp "assets/asset_2/stop_server_ext.json" "/etc/jupyter/jupyter_server_config.d//"
else
    mkdir -p "$(dirname "/etc/jupyter/jupyter_server_config.d/")"
    cp "assets/asset_2/stop_server_ext.json" "/etc/jupyter/jupyter_server_config.d/"
fi

# Asset 3: file assets/generic/stop_server_ext.json -> /srv/jupyter/
echo "Installing asset file assets/asset_3/stop_server_ext.json to /srv/jupyter/..."
if [ -d "/srv/jupyter/" ] || [[ "/srv/jupyter/" == */ ]]; then
    mkdir -p "/srv/jupyter/"
    cp "assets/asset_3/stop_server_ext.json" "/srv/jupyter//"
else
    mkdir -p "$(dirname "/srv/jupyter/")"
    cp "assets/asset_3/stop_server_ext.json" "/srv/jupyter/"
fi

# Asset 4: file assets/generic/jp_app_launcher.yaml -> $HOME/.local/share/jupyter/jupyter_app_launcher/
echo "Installing asset file assets/asset_4/jp_app_launcher.yaml to $HOME/.local/share/jupyter/jupyter_app_launcher/..."
if [ -d "$HOME/.local/share/jupyter/jupyter_app_launcher/" ] || [[ "$HOME/.local/share/jupyter/jupyter_app_launcher/" == */ ]]; then
    mkdir -p "$HOME/.local/share/jupyter/jupyter_app_launcher/"
    cp "assets/asset_4/jp_app_launcher.yaml" "$HOME/.local/share/jupyter/jupyter_app_launcher//"
else
    mkdir -p "$(dirname "$HOME/.local/share/jupyter/jupyter_app_launcher/")"
    cp "assets/asset_4/jp_app_launcher.yaml" "$HOME/.local/share/jupyter/jupyter_app_launcher/"
fi

# Asset 5: file assets/generic/post-start-hook -> /opt/environments
echo "Installing asset file assets/asset_5/post-start-hook to /opt/environments..."
if [ -d "/opt/environments" ] || [[ "/opt/environments" == */ ]]; then
    mkdir -p "/opt/environments"
    cp "assets/asset_5/post-start-hook" "/opt/environments/"
else
    mkdir -p "$(dirname "/opt/environments")"
    cp "assets/asset_5/post-start-hook" "/opt/environments"
fi

