#! /bin/bash -eu

export TEST_DIR=$COMMON_IMAGE_DIR/pkgs/git-sync-v4

cd $TEST_DIR

python -m pytest -v -v -v  \
       --tb=short \
       --capture=no \
       --log-level INFO --log-cli-level INFO \
       --doctest-modules \
       --doctest-report cdiff \
       --cov=git_sync_v4 --cov-report=html:htmlcov  \
       tests.py tests.txt $*

rm -rf __pycache__
